name: Deploy React App to DigitalOcean

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23.5.0'

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "dist/*"  
        target: "/var/www/rep-frontend"
        strip_components: 1
